### ISSUE TITLE
Consider using CSS grid for this project?

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-basic-ng#17]
I have been reading a few tutorials lately that make it seem like CSS grid is a really nice way to create "simple" multi-screen layouts for standard website structures.

# Example

For example, [here's a tutorial](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Realizing_common_layouts_using_CSS_Grid_Layout) that uses the "semantic" information of the major screen areas to build a CSS grid. Here's a little example of the rules they use:

```css
.wrapper {
  display: grid;
  gap: 20px;
  grid-template-areas:
    "header"
    "nav"
    "content"
    "sidebar"
    "ad"
    "footer";
}
```

and

```css
@media (min-width: 500px) {
  .wrapper {
    grid-template-columns: 1fr 3fr;
    grid-template-areas:
      "header  header"
      "nav     nav"
      "sidebar content"
      "ad      footer";
  }
  nav ul {
    display: flex;
    justify-content: space-between;
  }
}
```

I thought this was a nice and clean way to define a relatively complex layout but with an intuitive structure and semantics. Curious if you've looked into CSS grid at all, and what you think!
